border_width = 6
margin = [4, 4]
default_border_color = "#0f1014"
floating_border_color = "#9A3646"
focused_border_color = "#db9c9a"


col1 = "#7D274E"
col2 = "#6D384A"
col3 = "#A12B3A"
col4 = "#D82938"
col5 = "#F6553A"
col6 = "#9A3646"
col7 = "#db9c9a"
col8 = "#996d6b"
col9 = "#7D274E"
col10 = "#6D384A"
col11 = "#A12B3A"
col12 = "#D82938"
col13 = "#F6553A"
col14 = "#9A3646"
col15 = "#db9c9a"



background = "#0f1014"
foreground = "#db9c9a"
