border_width = 6
margin = [4, 4]
default_border_color = "#0b0904"
floating_border_color = "#6E8D70"
focused_border_color = "#efcd97"


col1 = "#614826"
col2 = "#4C5341"
col3 = "#9E5617"
col4 = "#905426"
col5 = "#D56C13"
col6 = "#6E8D70"
col7 = "#efcd97"
col8 = "#a78f69"
col9 = "#614826"
col10 = "#4C5341"
col11 = "#9E5617"
col12 = "#905426"
col13 = "#D56C13"
col14 = "#6E8D70"
col15 = "#efcd97"



background = "#0b0904"
foreground = "#efcd97"
