border_width = 6
margin = [4, 4]
default_border_color = "#02070C"
floating_border_color = "#919CAD"
focused_border_color = "#cad5e0"


col1 = "#597193"
col2 = "#157AC5"
col3 = "#788180"
col4 = "#6E89AA"
col5 = "#549AD3"
col6 = "#919CAD"
col7 = "#cad5e0"
col8 = "#8d959c"
col9 = "#597193"
col10 = "#157AC5"
col11 = "#788180"
col12 = "#6E89AA"
col13 = "#549AD3"
col14 = "#919CAD"
col15 = "#cad5e0"



background = "#02070C"
foreground = "#cad5e0"
