border_width = 6
margin = [4, 4]
default_border_color = "#0e191c"
floating_border_color = "#A8B8C2"
focused_border_color = "#cddde4"


col1 = "#35708B"
col2 = "#54778A"
col3 = "#6590A1"
col4 = "#60ACC4"
col5 = "#99A2A9"
col6 = "#A8B8C2"
col7 = "#cddde4"
col8 = "#8f9a9f"
col9 = "#35708B"
col10 = "#54778A"
col11 = "#6590A1"
col12 = "#60ACC4"
col13 = "#99A2A9"
col14 = "#A8B8C2"
col15 = "#cddde4"



background = "#0e191c"
foreground = "#cddde4"
