border_width = 6
margin = [4, 4]
default_border_color = "#121015"
floating_border_color = "#366797"
focused_border_color = "#a4bbca"


col1 = "#67505C"
col2 = "#99512F"
col3 = "#97645C"
col4 = "#C96D40"
col5 = "#CB8C5A"
col6 = "#366797"
col7 = "#a4bbca"
col8 = "#72828d"
col9 = "#67505C"
col10 = "#99512F"
col11 = "#97645C"
col12 = "#C96D40"
col13 = "#CB8C5A"
col14 = "#366797"
col15 = "#a4bbca"



background = "#121015"
foreground = "#a4bbca"
